name: Production
on: 
    workflow_dispatch:

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Build Docker Image
          run: .\build.demo.ps1
          shell: pwsh
        - name: Push Docker Image
          env:
            dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
          run: .\push.demo.ps1
          shell: pwsh